CREATE DATABASE DB_DATABASE;

CREATE USER DB_USER WITH SUPERUSER PASSWORD 'DB_PASSWORD';
ALTER ROLE postgres PASSWORD 'DB_PASSWORD';
CREATE USER DB_USER WITH REPLICATION ENCRYPTED PASSWORD 'DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE DB_DATABASE TO DB_USER;

CREATE USER DB_REPL_USER WITH REPLICATION ENCRYPTED PASSWORD 'DB_REPL_PASSWORD';

\connect DB_DATABASE;

CREATE TABLE IF NOT EXISTS emails (
    ID SERIAL PRIMARY KEY,
    email VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS phones (
    ID SERIAL PRIMARY KEY,
    phone VARCHAR(30) NOT NULL
);

INSERT INTO emails (email) VALUES
    ('user1@mail.ru'),
    ('user2@gmail.com');

INSERT INTO phones (phone_number) VALUES
    ('89995553535'),
    ('+78987776666');
